name: Version deletion

on: delete

jobs:
  delete:
    uses: stakater/.github/.github/workflows/branch_deleted.yaml@v0.0.170
    with:
      LATEST_DOC_VERSION: "0.1"
    secrets:
      GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
